server:
 port: 8080
spring:
 application:
  name: configserver
 cloud:
  config:
   server:
    native:
     searchLocation:D:\Trabajo\repogit\microservicios\configuration
 profiles:
  active: native
logging:
 file: logs/${spring.application.name}.log
 level:
  com.netflix.discovery: 'OFF'
  org.springframework.cloud: 'DEBUG'
  es.microservice: 'DEBUG'